import type { Metadata } from "next";

import Header from "./components/Header";
import Sidebar from "./components/Sidebar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="flex w-full">
          
          <div className="w-64">
            <Sidebar />
          </div>
          <div className="w-full">
            <main>
              <div className=" ">
                
                {children}
              </div>
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}